# Generated by Django 5.0.3 on 2024-03-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuseraccount_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuseraccount',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuseraccount',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
