# Generated by Django 5.0.3 on 2024-03-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuseraccount_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuseraccount',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuseraccount',
            name='id_back',
            field=models.ImageField(null=True, upload_to='images/id_cards'),
        ),
        migrations.AlterField(
            model_name='customuseraccount',
            name='id_front',
            field=models.ImageField(null=True, upload_to='images/id_cards'),
        ),
        migrations.AlterField(
            model_name='customuseraccount',
            name='image',
            field=models.ImageField(null=True, upload_to='images/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='customuseraccount',
            name='zipcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
