# Generated by Django 5.0.3 on 2024-03-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuseraccount_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuseraccount',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuseraccount',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuseraccount',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='images/id_cards'),
        ),
        migrations.AlterField(
            model_name='customuseraccount',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='images/id_cards'),
        ),
        migrations.AlterField(
            model_name='customuseraccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='customuseraccount',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
