# Generated by Django 5.0.3 on 2024-04-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_incident_name_of_incident_incidentaccess_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentimage',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='incidentlog',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='viewcrimescenerequest',
            options={'ordering': ['-id']},
        ),
    ]
